name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag petrycht/nes-emu:$(date +%s)
    - name: Push the image
      run: docker push petrycht/nes-emu:$(date +%s)
